config/routes.rb
GetLit::Application.routes.draw do

  namespace :admin do
    resources :shelves, :except => %w(show)
    resources :drinks, :only => %w(index edit update)
  end
  
  get '/search', :to => 'searches#show'
  get '/:title', :to => 'searches#show'
  root :to => 'searches#new'
end

app/models/drink.rb
class Drink < ActiveRecord::Base

  TYPES = %w(beer highball wine teapot cocktail shots testtube lowball)

  self.include_root_in_json = false

  has_many :shelves

  validates_presence_of :name

  def self.options_for_drink_type_select
    TYPES.map do |type|
      [
        I18n.t("activerecord.labels.drink.drink_type.#{type}"),
        type
      ]
    end
  end
end

app/models/shelf.rb
class Shelf < ActiveRecord::Base
  belongs_to :drink

  validates_presence_of :name

  accepts_nested_attributes_for :drink
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    layout 'admin'
    before_filter :authenticate

    private

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == 'admin' &&
          Digest::MD5.hexdigest(password) == 'e954ec556c8754691da9e11eabefaf90'
      end
    end
  end
end

app/controllers/admin/drinks_controller.rb
module Admin
  class DrinksController < AdminController
    before_filter :load_drink, :only => %w(edit update)

    def index
      @drinks = Drink.order('name ASC').page(params[:page] || 1).per(20)
    end

    def edit
    end

    def update
      @drink.update_attributes!(params[:drink])
      redirect_to admin_drinks_path
    rescue ActiveRecord::RecordInvalid
      render :action => :edit
    end

    private

    def load_drink
      @drink = Drink.find(params[:id])
    end
  end
end

app/controllers/admin/shelves_controller.rb
module Admin
  class ShelvesController < AdminController
    before_filter :load_shelf, :only => %w(edit update destroy)
    before_filter :sanitize_params, :only => %w(create)

    def index
      @shelves = Shelf.includes(:drink).order('name ASC').page(params[:page] || 1).per(20)
    end

    def new
      @shelf = Shelf.new
    end

    def create
      @shelf = Shelf.new(params[:shelf])
      @shelf.save!
      redirect_to admin_shelves_url
    rescue ActiveRecord::RecordInvalid
      render :action => :new
    end

    def edit
    end

    def update
      @shelf.update_attributes!(params[:shelf])
      redirect_to admin_shelves_url
    rescue ActiveRecord::RecordInvalid
      render :action => :edit
    end

    def destroy
      @shelf.destroy
      redirect_to admin_shelves_url
    end

    private

    def load_shelf
      @shelf = Shelf.find(params[:id])
    end

    def sanitize_params
      if params[:shelf][:drink_id].present?
        params[:shelf].delete(:drink_attributes)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
  end

  def show
    title = params[:title]
    if title
      @book = Rails.cache.fetch("book/#{title.downcase.gsub(/\W+/, '-')}") do
        results = GoodReads.search_books(:title, title)
        if results.any?
          book = GoodReads.get_book(results.first.id)
        end
      end

      if @book
        if @book.popular_shelves.present?
          shelves_by_name = {}
          Shelf.where(:name => @book.popular_shelves).where('drink_id IS NOT NULL').each do |shelf|
            shelves_by_name[shelf.name] = shelf
          end
          if shelves_by_name.any?
            @shelf = nil
            @book.popular_shelves.each do |name|
              break if @shelf = shelves_by_name[name]
            end
            @drink = @shelf.drink
          end
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def dom_class_for_controller
    params[:controller].split('/').map { |c| c.camelize }.join(' ')
  end

  def dom_id_for_action
    params[:action].camelize
  end

  def twitter_share_link(book, drink)
    status = "Enjoying #{book.title} with a #{drink.name} on the side. http://#{request.host_with_port}/#{book.title}"
    URI::HTTP.build(
      :host => 'twitter.com',
      :path => '/home',
      :query => { :status => status }.to_query
    ).to_s
  end

  def facebook_share_link(book, drink)
    url =  "http://#{request.host_with_port}/#{book.title}"
    URI::HTTP.build(
      :host => 'www.facebook.com',
      :path => '/share.php',
      :query => {:u => url}.to_query
    ).to_s
  end
end

app/views/admin/drinks/_form.html.haml
%div= form.label :name, Drink.human_attribute_name(:name)
%div= form.text_field :name
%div= form.label :drink_type
%div= form.select :drink_type, Drink.options_for_drink_type_select
%div= form.label :recipe
%div= form.text_area :recipe_html, :class => 'recipe_html'
:javascript
  $(function () {
    $('.recipe_html').tinymce({ theme: 'advanced' });
  });

app/views/admin/drinks/edit.html.haml
- if @drink.errors.any?
  %ul.errors
    - @drink.errors.full_messages.each do |message|
      %li= message
= form_for [:admin, @drink] do |form|
  = render :partial => 'form', :object => form
  %div= form.submit t('.submit')

app/views/admin/drinks/index.html.haml
%ul.drinks
  - @drinks.each do |drink|
    %li
      .drink= link_to drink.name, edit_admin_drink_path(drink)
%p.pagination= paginate @drinks

app/views/admin/shelves/_form.html.haml
%div= form.label :name
%div= form.text_field :name
%div= form.label :explanation
%div= form.text_area :explanation
%div= form.label :drink
%div= form.collection_select :drink_id, Drink.all, :id, :name, :include_blank => t('.new_drink')

app/views/admin/shelves/edit.html.haml
- if @shelf.errors.any?
  %ul.errors
    - @shelf.errors.full_messages.each do |message|
      %li= message

= form_for [:admin, @shelf] do |form|
  = render :partial => 'form', :object => form
  %div
    = form.submit t('.submit')

app/views/admin/shelves/index.html.haml
%p.new= link_to t('.new'), new_admin_shelf_path
%ul.shelves
  - @shelves.each do |shelf|
    %li
      .shelf= link_to shelf.name, edit_admin_shelf_path(shelf)
      - if shelf.drink
        .drink= shelf.drink.name
      .destroy
        = form_tag admin_shelf_path(shelf), :method => 'delete' do
          = submit_tag t('.destroy')
%p.pagination= paginate @shelves

app/views/admin/shelves/new.html.haml
- if @shelf.errors.any?
  %ul.errors
    - @shelf.errors.full_messages.each do |message|
      %li= message

= form_for [:admin, @shelf] do |form|
  .shelf= render :partial => 'form', :object => form
  .drink
    = form.fields_for :drink_attributes, form.object.drink do |drink_fields|
      = render :partial => 'admin/drinks/form', :object => drink_fields
  .submit
    = form.submit t('.submit')

app/views/layouts/admin.html.haml
%html
  %head
    %title Get Lit Super CMS
    = stylesheet_link_tag 'admin'
    = javascript_include_tag 'admin'

  %body{ :class => dom_class_for_controller, :id => dom_id_for_action }
    #content= yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      = t 'global.site_name'
      - if @book
        &ndash;
        = @book.title
    %meta{"http-equiv" => "Content-Type", :content => "text/html; charset=utf-8"}
    %meta{:name => "language", :content => "en"}
    %meta{:name => "description", :content => "Get Lit!"}
    %meta{:name => "keywords", :content => "literature, books, drink, mixology, liquor, alcohol, beer, read, well-read, cocktail, scholarly"}

    = favicon_link_tag '/assets/favicon.ico'
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{ :class => dom_class_for_controller, :id => dom_id_for_action }
    #wrapper
      %a{:href => '/'}
        #header
      = yield

app/views/searches/_types.html.haml
.thin-col
  - for type in types
    .drink-type{:class=>@drink.try(:drink_type) == type ? 'active' : 'not-active'}
      .drink{:id=>type}

app/views/searches/new.html.haml
= render :partial => 'types', :object => Drink::TYPES[0...4]

.main
  #logo
  .content#home
    %h1 What are you reading?
    %form#search(action="search")
      %input.title-input{:type => "text", :name => "title", :placeholder => "Book title"}
      %button.recommend{:type => "submit"} What should I drink?

= render :partial => 'types', :object => Drink::TYPES[4..-1]

app/views/searches/show.html.haml
= render :partial => 'types', :object => Drink::TYPES[0...4]

.main
  #logo
  - if @book
    .content#book
      .cover
        %img{:src => @book.image_url}
      .recipe
        %h1== You're reading #{@book.title}.
        - if @drink
          %h2 How about sipping on a #{@drink.name}?
          - if @drink.recipe_html.present?
            = raw @drink.recipe_html
          - if @shelf.explanation.present?
            %p.explanation= @shelf.explanation
        - else
          %h2 We've never heard of it. Grab a couple shots of the cheap stuff and soldier on.
  - else
    .content.notfound#book
      .recipe
        %h1== #{params[:title]}? Never heard of it. Grab a couple shots of the cheap stuff and soldier on.

= render :partial => 'types', :object => Drink::TYPES[4..-1]
.footer
  - if @book && @drink
    .social
      %a.social-button{:href => twitter_share_link(@book, @drink)}
        %img{:src => "/assets/twitter.png"}
      %a.social-button{:href => facebook_share_link(@book, @drink)}
        %img{:src => "/assets/facebook.png"}
  %a.recommend{:href => "/"} I'm also reading...